name: Run Kuksa Lib Tests
description: Runs Unit and Integration Test. Tests will be executed on a Databroker instance.

inputs:
  databroker-version:
    description: "Databroker Version"
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: "Run insecure Databroker in detached mode"
      run: docker run --pull=always --rm --publish 55556:55556/tcp --detach --name databroker ghcr.io/eclipse-kuksa/kuksa-databroker:${{ inputs.databroker-version }} --port 55556 --insecure
      shell: bash

    - name: Run cargo tests against insecure databroker
      working-directory: lib
      run: "cargo test -- :insecure:"
      shell: bash

    - name: "Stop insecure Databroker"
      if: always()
      run: docker stop databroker
      shell: bash

    - name: "Run Databroker with authentication enabled in detached mode"
      run: docker run --pull=always --rm --publish 55556:55556/tcp -v ${{github.workspace}}/certificates:/certs --detach --name databroker ghcr.io/eclipse-kuksa/kuksa-databroker:${{ inputs.databroker-version }} --port 55556 --insecure --jwt-public-key /certs/jwt/jwt.key.pub
      shell: bash

    - name: Run cargo tests with authentication enabled
      working-directory: lib
      run: "cargo test -- :authentication:"
      shell: bash

    - name: "Stop Databroker with authentication enabled"
      if: always()
      run: docker stop databroker
      shell: bash
